### ISSUE TITLE
Dragons break armor

### ISSUE THREAD

**Issue by Vyacheslav73195** [EricLangezaal/PetDragon#12]
When using this plugin, we accidentally discovered that dragons break armor enchanted with spikes. This happens even when damage to entities, blocks, etc. disabled. (including the owner of the dragon).
We'd like you to fix this as it really interferes with the use of this plugin.

**Comment by EricLangezaal** [comment]
Hi! As weird as it might sound, I am actually aware of this inconsistency, which is caused because the Thorns enchantment overwrites a lot of damage logic.
 
This was reported quite a while ago for the premium counterpart of this plugin, and through debugging with some experienced customers we managed to find out this issue was quite complex internally. In the end I was able to fix it, but it did require me to rewrite the entire damage logic for the premium plugin. Since this took so much time and wasn't a simple bugfix but rather a complete rework, the feature to handle thorns is currently only present in the Premium (paid) product, I encourage you to [check it out](https://www.spigotmc.org/resources/99995/). I might one day rework this plugin too, but since that requires quite some work and this is a free work, I do not know if/when I will do so.
