### ISSUE TITLE
Higher Range vor /dragon remove

### ISSUE THREAD

**Issue by CloudeLecaw** [EricLangezaal/PetDragon#4]
Add a higher range for /dragon remove

it woud be nice if we could set this up in the console
sometimes we would need a radius of 5 blocks or may 6...
specialy when players "ram" their dragon a bit deeper into the bottom

currently we are forced to 3 blocks

**Comment by EricLangezaal** [comment]
Hi again!
O yes good idea, never thought about it. I will probably just make it so that the command accepts it as an argument, something like `/dragon remove 5` (with a limit of 20 or something to prevent it from being a lag generator). I don't know when I have the time to create this new update yet.

**Comment by EricLangezaal** [comment]
And done! I found some time to do this in between other stuff, so I implemented this along with an update checker (have wanted to add that for a long time). If you like the new version you can leave a review if you want. This is kind of my 'flagship' plugin haha, so I look at its reviews more:).
