### ISSUE TITLE
Unable to use PetDragonAPI class

### ISSUE THREAD

**Issue by JonesPawa** [EricLangezaal/PetDragon#7]
I can't use the PetDragonAPI in my code, because it can't find the PetDragonAPI class . 
I have tried both ways to import it with maven. The local repository approach as well as the system dependency with a link to the file itself. The jar file "PetDragon-1.5.3.jar" is also displayed with its subfolders in Intellij in the External Libraries and I also used the "Download Sources and Documentation" button.

Since I had no problems with other jar files like "The API": https://github.com/TheDevTec/TheAPI, I'm not sure what the problem could be. Is there anything else you need to do to use the API?

**Comment by EricLangezaal** [comment]
The problem seems to be that the API jar doesn't contain any code, but purely sources. I thought Maven should be clever enough to handle that (since it literally suggests making a separate API jar) but apparently not. I have just spend about an hour trying to get Maven to create a proper API jar, but it just doesn't work. So for now I advise just building against the released Jar on Spigot (same group id and artifact id). It's a shame, because that doesn't include any Javadoc. You can still use the source code on GitHub for documentation though. 

I will try update the wiki soon if I find a better solution.

**Comment by JonesPawa** [comment]
Thanks for the quick response and the tip to use the version published on Spigot. Since I would like to use the Plugin, it is a good workaround, even without Javadoc.
