### ISSUE TITLE
it is possible to decrease the height of the "saddle"

### ISSUE THREAD

**Issue by haroldrc** [EricLangezaal/PetDragon#8]
it is possible to decrease the height of the "saddle"

**Comment by EricLangezaal** [comment]
This is unfortunately a client side problem with the way how Minecraft renders passengers of certain entities. I have researched this extensively and consulted with some other developers on the issue, but there is no way to change it without modifying the client. Below I have pasted a more in-depth explanation which I gave to a similar question recently:

Yes I definitely agree the current passenger position isn't beautiful at all and have gotten suggestions to change it in the past. However due to the way my plugin works, this is not possible at all. Unlike similar plugins, I actually let the players be a passenger of the dragon (as opposed to for example letting them ride an armor stand which is teleported near the dragon), as this has less rubber banding, is more performant and means you can see the dragons health bar.

However, this means that we are stuck with the defined passenger position. I have researched this extensively, and unfortunately it is 100% clientsided. Since the player is a passenger, sending packets that try to change the player's position alone have no effect, Minecraft will base its position on that of the vehicle. And if I were to fake the position of the dragon using packets, the player will simply be rendered upwards as well. Unfortunately this is a result of how Minecraft handles entities that are a passenger. The only way to get around it is the aformentioned armor stand solution, but that has far more downsides
